console.log('Hola mundo, ¡Estoy trabajando con control de versiones git!')
console.log('Esta es una caracteristica')
console.log('Esta es una caracteristica2')
console.log('Esta es una caracteristica3')
console.log('Esta es una caracteristica4')
console.log('Esta es una caracteristica5')
